running: dev
domain: http://ec2-43-200-172-178.ap-northeast-2.compute.amazonaws.com:8080
S3domain: http://izonestorage.s3-website.ap-northeast-2.amazonaws.com:80

spring:
  profiles:
    include: common
    active: dev
kakao:
  key: ${KAKAO_KEY}
server:
  servlet:
    encoding:
      charset: UTF-8
  datasource:
    url: ${datasource_url}
    username: ${datasource_username}
    password: ${datasource_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.hibernate.SQL: trace

jwt:
  secret: ${secret_key}
  access-token-expiration-minutes: 1800000
  refresh-token-expiration-minutes: 604800000

mail:
  address:
    admin: ${admin_mail}

